name: fungalflye
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - flye
  - minimap2
  - racon
  - seqkit
  - filtlong
  - pandas
  - matplotlib
  - biopython
  - typer
  - pip
  - pip:
      - git+https://github.com/beyhanlab/FungalFlye.git