#!/usr/bin/env python3

from .Collisions import RefCollisions, SortLoci
from .Gff3 import Gff3file
from .Locus import Locus, spanningLocus
from .Sequence import DnaSequence, ProteinSequence

from hashlib import sha1

class Genome:
    """The set of DNA sequences specifying an organism,
    plus higher order features derived from that sequence
    (e.g. genes, repeats, transposons, etc.).  Also,
    higher order features resulting from external designs
    based on the sequence (e.g. microarray oligo sets)."""

    class Error(BaseException):
        def __init__(self, e = "Genome Error"):
            self.e = e
        def __repr__(self):
            return self.e
        def __str__(self):
            return self.e

    def __init__(self, name, contigs, genes):
        """Init from .GenomeAssembly and GeneSet."""
        self.name = name
        self.contigs = contigs
        self.genes = genes
        self.gene_index = None
        # Removed genes.  This will probably be moved to GeneSet
        self.removed = []
        # Added genes.  This will probably be moved to GeneSet
        self.new_genes = []
        
    @property
    def genetic_code(self):
        """Return name of alternate genetic code or None for universal
        genetic code."""
        return None

    def Name(self):
        return self.name

    # Replace Genes() and Contigs() with iterators?

    def Genes(self):
        """Iterator over all genes in the genome."""
        return self.genes.items()

    def getGene(self, name):
        """Get a gene by name lookup.
        Name will be cleaned up based on gene set specific oddities.
        Returns None if no gene is found.
        Throws an exception on ambiguous name matching.
        """
        try:
            try:
                name = genefix[self.Name()](name)
            except:
                pass
            
            return self.genes[name]
        except KeyError:
            return None

    def get_gene_by_sha(self, sha):
        """Get a gene by the first 12 hexidecimal digits of the sha1 digest of
        its name (e.g., as generated by Blastxml2inparanoid.py and
        InparanoidCrunch.py)
        """
        try:
            return self.__sha2gene[sha]
        except AttributeError:
            if(self.genes is None):
                self._initGenes()
            self.__sha2gene = dict((i.sha1_12(),i) for i in self.genes.values())

            return self.__sha2gene[sha]

    def getGenesByLocus(self, locus):
        """Return a list of genes with _any_ overlap to locus."""
        if(self.gene_index is None):
            self.gene_index = SortLoci(self.genes.values())
        
        return RefCollisions((locus,), self.gene_index).OverlapA(locus)
        
    def Contigs(self):
        """Iterator over all contigs in the genome."""
        # TODO: make this more iterator-like?
        return self.contigs.items()

    def GetContig(self, name):
        """Get a contig by name lookup."""
        return self.contigs[name]

    def GetSequence(self, locus):
        """Returns the genomic sequence corresponding to locus.
        If locus extends past either edge of the contig given
        by locus.ref, sequence is returned for locus truncated
        to the contig edges (analogous to string.__getslice__)."""

        # We implement 5' clipping here to avoid issues with negative
        # slicing indices.  3' clipping is currently implimented downstream
        # do avoid requiring (possibly expensive) implementation of __len__
        # for contigs.  TODO: rethink this.
        seq = self.contigs[locus.ref][max(0,locus.start - 1):locus.stop]
        
        if(locus.strand == "-"):
            return seq.Complement()

        return seq

    def Translate(self, seq, from_start = False):
        """Translate Sequence using any special translation rules
        for this Genome.  Defaults to letting the sequence translate
        itself (which is not necessarily the same as defaulting to
        the universal genetic code)."""
        return seq.Translate(genetic_code = self.genetic_code,
                             from_start = from_start)

    def writeGbrowse2Gff3(self, fout, source = "GeneSet"):
        """Write the coordinates of the gene set to fout
        in Gbrowse2-compatible GFFv3 format.
        (See MemGeneSet.fromGbrowse2Gff3 for a detailed
         specification of this format).
        Gene order in the file and CDS numbering follows lexical sort of
        gene names.
        """
        cdsID = 0

        for (name, gene) in sorted(self.Genes()):
            cdsID = gene.writeGbrowse2Gff3(fout, cdsID = cdsID, source = source)

    def writeFlairGtf(self, fout, source = "GeneSet"):
        """Write the coordinates of the gene set to fout
        in FLAIR-compatible GTF format
        Gene order in the file and CDS numbering follows lexical sort of
        gene names.
        """
        cdsID = 0

        for (name, gene) in sorted(self.Genes()):
            cdsID = gene.writeFlairGtf(fout, cdsID = cdsID, source = source)
            
    def protein_fasta_stream(self):
        print("Dumping FASTA")
        fname = "Lucien2_hack.%s.fasta" % self.name
        fp = open(fname,"w")
        for (name, gene) in self.Genes():
            if(len(gene.Cds()) > 0):
                fp.write(gene.ProteinSequence().FormatFasta(name = name))
        print("Dumped it")
        return open(fname)
            
class GenomeAssembly:
    """The set of contig sequences corresponding to a (potentially partial)
    genome assembly."""

    class Error(BaseException):
        def __init__(self, e = "GenomeAssembly error"):
            self.e = e
        def __repr__(self):
            return self.e
        def __str__(self):
            return self.e

    def __len__(self):
        """Number of contigs in assembly"""
        raise GenomeAssembly.Error("__len__() not implemented")

    def __getitem__(self, i):
        """Get contig by name.  Returns a DnaSequence object."""
        raise GenomeAssembly.Error("__getitem__(i) not implemented")

    def items(self):
        """Return all contigs as (name, DnaSequence) pairs"""
        raise GenomeAssembly.Error("items() not implemented")

class MemGenomeAssembly(GenomeAssembly):
    """GenomeAssembly where sequences are stored in memory."""
    def __init__(self, contigs = None, fasta = None):
        """Initialize from map<string, DnaSequence>"""
        if(contigs == None):
            contigs = {}
        self.contigs = contigs

        if(fasta != None):
            self.LoadFasta(fasta)

    def __len__(self):
        """Number of contigs in assembly"""
        return len(self.contigs)

    def __getitem__(self, i):
        """Get contig by name.  Returns a DnaSequence object."""
        return self.contigs[i]

    def items(self):
        """Return all contigs as (name, DnaSequence) pairs"""
        return self.contigs.items()

class Gene:
    class Error(BaseException):
        def __init__(self, e = "Gene error"):
            self.e = e
        def __repr__(self):
            return self.e
        def __str__(self):
            return self.e

    # Two genes are the same if they have the same name.
    # I.e., we assume that names are sufficiently unique
    # such that equivalent names implies equivalent loci,
    # gene structure, and sequence.  Given that much of
    # the system depends on name based lookup, this is
    # a reasonable assumption.

    def __eq__(self, rhs):
        if(isinstance(rhs, Gene)):
            return self.Name() == rhs.Name()
        else:
            return 0

    # If equality is defined on gene name, the sorting genes
    # should give a lexical sort

    def __le__(self, rhs):
        return self.Name().__le__(rhs.Name())
    def __lt__(self, rhs):
        return self.Name().__lt__(rhs.Name())
    def __ge__(self, rhs):
        return self.Name().__ge__(rhs.Name())
    def __gt__(self, rhs):
        return self.Name().__gt__(rhs.Name())
    def __ne__(self, rhs):
        if(isinstance(rhs, Gene)):
            return self.Name() == rhs.Name()
        else:
            return True
            
    def __hash__(self):
        return hash(str(self.Name()))

    def __repr__(self):
        return self.Name()

    @property
    def long_name(self):
        """Tuple of (genome name, gene name) strings.  Intended as
        unique identifier (which will be the case if gene names are
        unique within genomes and if genome names are globally unique).

        Raises exception for genes not associated with genomes.
        """
        return (str(self.Locus().genome.name),str(self.Name()))

    def Name(self):
        """Gene name as string"""
        raise Gene.Error("Name not implemented")

    def sha1_12(self):
        """Return first 12 (hex) characters of SHA1 digest of name.

        This is a safe stable name to use for programs such as
        CLUSTAL, INPARANOID, and MochiView that can't handle
        arbitrarily long gene names."""

        # TODO: Any global name-normalizing rules should go here
        #       (e.g., fixes for "final" vs. "final_new" in G186AR (GSC))
        
        return sha1(self.Name().encode()).hexdigest()[:12]

    def Locus(self):
        """Return locus struct"""
        raise Gene.Error("Locus not implemented")

    def Exons(self):
        """Return exons as (first, last) list relative to genomic seq."""
        raise Gene.Error("Exons not implemented")

    def ExonLoci(self):
        """Return exons as list of loci relative to contig."""
        locus = self.Locus()
        if(locus.strand == "-"):
            return [Locus(ref = locus.ref,
                          start = locus.stop - last + 1,
                          stop = locus.stop - first + 1,
                          strand = "-",
                          genome = locus.genome)
                    for (first, last) in self.Exons()]
        else:
            return [Locus(ref = locus.ref,
                          start = locus.start + first - 1,
                          stop = locus.start + last - 1,
                          strand = "+",
                          genome = locus.genome)
                    for (first, last) in self.Exons()]
        
    def Cds(self):
        """Return cds regions as (first, last) list relative to transcript seq."""
        raise Gene.Error("Cds not implemented")

    def CdsLoci(self):
        """Return cds regions as a list of Locus instances relative to the
        genomic sequence, but sorted relative to their order of transcription
        (i.e., minus strand transcripts have their CdsLoci ordered right
        to left).
        """
        # Map exons to transcript coordinates, retaining back references
        # to genome coordinates
        
        class MappedExon:
            def __init__(self, tloc, gloc):
                self.tloc = tloc
                self.gloc = gloc
            def Locus(self):
                return self.tloc.Locus()
        
        locus = self.Locus()
        texons = []
        tpos = 1
        for exon in self.ExonLoci():
            npos = tpos + len(exon) - 1
            texons.append(MappedExon(
                Locus(ref = "transcript",
                      start = tpos,
                      stop = npos,
                      strand = "+",
                      genome = None),
                exon))
            tpos = npos+1

        # Take the intersection of the exons with the cds in
        # transcript space, and return the corresponding loci
        # in genome space.  Currently, we do an exhaustive
        # comparison of all exons to all cds.  There should
        # be a more elegant solution given both as sorted lists...

        retval = []
        for (cstart, cstop) in self.Cds():
            cloc = Locus(ref = "transcript",
                         start = cstart,
                         stop = cstop,
                         strand = "+",
                         genome = None)

            for exon in texons:
                overlap = exon.Locus().Overlap(cloc)
                # Case 1: no overlap --> ignore this exon wrt this cds
                if(overlap < 1):
                    continue
                # Case 2: full overlap --> this full exon propagates to output
                elif(overlap == len(exon.Locus())):
                    retval.append(exon.gloc)
                # Case 3: partial overlap --> make corresponding slice in
                #         genome space
                else:
                    if(cloc.start > exon.tloc.start):
                        start = cloc.start - exon.tloc.start + 1
                    else:
                        start = 1
                    if(cloc.stop < exon.tloc.stop):
                        # N.B.: overlap implies cloc.stop >= tloc.start
                        stop = cloc.stop - exon.tloc.start + 1
                    else:
                        stop = len(exon.tloc)

                    if(exon.gloc.strand == "+"):
                        retval.append(
                            Locus(ref = exon.gloc.ref,
                                  start = exon.gloc.start + start - 1,
                                  stop = exon.gloc.start + stop - 1,
                                  strand = "+",
                                  genome = exon.gloc.genome))
                    else:
                        retval.append(
                            Locus(ref = exon.gloc.ref,
                                  start = exon.gloc.stop - stop + 1,
                                  stop = exon.gloc.stop - start + 1,
                                  strand = "-",
                                  genome = exon.gloc.genome))
        return retval

    def utr_seqs(self):
        """Return a tuple of DnaSequences for the 5' and 3' UTR of
        this gene.  Return empty sequences for missing UTRs.  Raise a
        ValueError for non-coding genes.  If the gene contains a stop
        codon, it will be included in the 3' UTR.
        """
        return tuple(DnaSequence("".join(str(locus.Sequence())
                                         for locus in i))
                     for i in self.utr_loci())
    
    def utr_loci(self):
        """Return a tuple of lists of loci for the 5' and 3' UTR
        respectively.  If this gene contains a stop codon, that codon
        will be included in the 3' UTR.  If this gene contains no
        coding sequence, raise a ValueError.  As for ExonLoci and
        CdsLoci, the loci will be sorted in 5'->3' order."""
        
        exons = self.ExonLoci()
        cds = self.CdsLoci()
        if(len(cds) == 0):
            raise ValueError
            
        utr5 = []
        utr3 = []
        if(self.Locus().strand == "+"):
            for (n,exon) in enumerate(exons):
                if(cds[0].start > exon.stop):
                    utr5.append(exon)
                elif(cds[0].start == exon.start):
                    break
                else:
                    utr5.append(
                        Locus.fromPrototype(exon, stop = cds[0].start-1))
                    break
            else:
                raise AssertionError("CDS don't overlap exons")
            for exon in exons[n:]:
                if(cds[-1].stop >= exon.stop):
                    continue
                elif(cds[-1].stop >= exon.start):
                    assert(len(utr3) == 0)
                    utr3.append(
                        Locus.fromPrototype(exon, start = cds[-1].stop+1))
                else:
                    utr3.append(exon)
            
        else: # minus strand
            # cds ands exons are both sorted 5'->3'
            for (n,exon) in enumerate(exons):
                if(cds[0].stop < exon.start):
                    utr5.append(exon)
                elif(cds[0].stop == exon.stop):
                    break
                else:
                    utr5.append(
                        Locus.fromPrototype(exon, start = cds[0].stop+1))
                    break
            else:
                raise AssertionError("CDS don't overlap exons")
            for exon in exons[n:]:
                if(cds[-1].start <= exon.start):
                    continue
                elif(cds[-1].start <= exon.stop):
                    assert(len(utr3) == 0)
                    utr3.append(
                        Locus.fromPrototype(exon, stop = cds[-1].start-1))
                else:
                    utr3.append(exon)

        return (utr5,utr3)
                    
    def SetExons(self, exons):
        """Set exons to (first, last) list."""
        raise Gene.Error("SetExons not implemented")

    def SetCds(self, cds):
        """Set cds to (first, last) list."""
        raise Gene.Error("SetCds not implemented")

    def GenomicSequence(self):
        """Return genomic sequence."""
        # Note: consider adding lazy evaluation at the genome level
        return self.Locus().Sequence()

    def TranscriptSequence(self):
        """Return transcript sequence."""
        # TODO: move this to a "splice" function at the Sequence level
        return DnaSequence(
            "".join(map(lambda x : str(self.GenomicSequence()[x[0]-1:x[1]]),
                        self.Exons())))

    def CodingSequence(self, add_stop = False):
        """Return cds sequence."""
        seq = "".join(map(lambda x : str(self.TranscriptSequence()[x[0]-1:x[1]]),
                          self.Cds()))
        if(add_stop):
            if(not self.has_stop_codon):
                raise ValueError("No stop codon for %s!" % (self.Name()))
            seq += str(self.StopCodonSequence())
            
        return DnaSequence(seq)

    def StopCodonSequence(self):
        """Return the codon immediately following the last CDS base in
        this transcript.  Don't check if the returned value is a valid
        stop codon.  Return zero to two bases for a truncated stop.
        """
        last = self.Cds()[-1][1]
        return self.TranscriptSequence()[last:last+3]

    def has_stop_codon(self):
        """Return True if the codon immediately following the last CDS base
        in this transcript would be translated as a stop codon in the native
        genome.
        """
        return str(self.Locus().genome.Translate(self.StopCodonSequence())
                   ) == "*"

    def ProteinSequence(self):
        """Return translated cds sequence.  May include internal stops."""
        # Note: We let Genome do the translation so that different
        #       species can use different genetic codes
        #       We set from_start to handle non-canonical initiators
        #       (e.g. C. albicans)
        return self.Locus().genome.Translate(self.CodingSequence(),
                                             from_start = True)

    def splice_junctions(self):
        """Return a list of four character splice junction sequences."""
        seqs = []
        exon_loci = self.ExonLoci()
        for i in range(len(exon_loci) - 1):
            l1 = exon_loci[i]
            l2 = exon_loci[i+1]
            if(self.Locus().strand == "+"):    
                seq = (str(Locus.fromPrototype(
                    l1, start = l1.stop+1, stop = l1.stop+2).Sequence())+
                       str(Locus.fromPrototype(
                    l2, start = l2.start-2, stop = l2.start-1).Sequence()))
            else:
                # Note that strand of exon locus automatically gives
                # complementation
                seq = (str(Locus.fromPrototype(
                    l1, start = l1.start-2, stop = l1.start-1).Sequence())+
                       str(Locus.fromPrototype(
                    l2, start = l2.stop+1, stop = l2.stop+2).Sequence()))
            seqs.append(seq)
        return seqs

    def writeGbrowse2Gff3(self, fout, cdsID = 0, source = "GeneSet"):
        """Write the coordinates of this to fout
         in Gbrowse2-compatible GFFv3 format.
         (See MemGeneSet.fromGbrowse2Gff3 for a detailed
          specification of this format)
         The cdsID parameter gives the highest cdsID currently used in fout.
         Return the last cdsID for this gene.
         (N.B.: Current model is that every gene has _exactly_ one reading
          frame, generated by concatenating the CDS features)
         """
        # transcript
        fout.write("\t".join((
            self.Locus().ref,
            source,
            "gene",
            "%d" % self.Locus().start,
            "%d" % self.Locus().stop,
            ".",
            self.Locus().strand,
            ".",
            "ID=%s;Name=%s" % (self.Name(),self.Name())))+"\n")

        # exons
        for exon in self.ExonLoci():
            fout.write("\t".join((
                exon.Locus().ref,
                source,
                "exon",
                "%d" % exon.Locus().start,
                "%d" % exon.Locus().stop,
                ".",
                exon.Locus().strand,
                ".",
                "Parent=%s" % self.Name()))+"\n")

        # cds
        cdsID += 1
        for cds in self.CdsLoci():
            fout.write("\t".join((
                cds.Locus().ref,
                source,
                "cds",
                "%d" % cds.Locus().start,
                "%d" % cds.Locus().stop,
                ".", # score
                cds.Locus().strand,
                "0", # phase
                "ID=cds%07d;Parent=%s" % (cdsID,self.Name())))+"\n")

        return cdsID

    def writeFlairGtf(self, fout, cdsID = 0, source = "GeneSet"):
        """Write the coordinates of this gene to fout
        in FLAIR-compatible GTF format.
        """

        # transcript
        fout.write("\t".join((
            self.Locus().ref,
            source,
            "gene",
            "%d" % self.Locus().start,
            "%d" % self.Locus().stop,
            ".",
            self.Locus().strand,
            ".",
            'trancript_id "%s"' % self.Name()))+"\n")

        # exons
        for exon in self.ExonLoci():
            fout.write("\t".join((
                exon.Locus().ref,
                source,
                "exon",
                "%d" % exon.Locus().start,
                "%d" % exon.Locus().stop,
                ".",
                exon.Locus().strand,
                ".",
                'transcript_id "%s"' % self.Name()))+"\n")

        # cds
        cdsID += 1
        for cds in self.CdsLoci():
            fout.write("\t".join((
                cds.Locus().ref,
                source,
                "CDS",
                "%d" % cds.Locus().start,
                "%d" % cds.Locus().stop,
                ".", # score
                cds.Locus().strand,
                "0", # phase
                'ID=cds%07d;transcript_id "%s"' % (cdsID,self.Name())))+"\n")

        return cdsID
    
class MemGene(Gene):
    """In-memory implementation of Gene"""
    def __init__(self, name, locus, exons = None, cds = None):
        self.__name = name
        self.__locus = locus
        self.__exons = exons
        if(self.__exons is None):
            self.__exons = []
        self.__cds = cds
        if(self.__cds is None):
            self.__cds = []

    @classmethod
    def fromExonLoci(cls, exon_loci, name, genome = None):
        """Construct a MemGene from a list of contig-based exon coordinates."""
        exon_loci = list(exon_loci)
        refloc = exon_loci[0].Locus()
        if(genome is None):
            genome = refloc.genome

        locus = Locus.fromPrototype(spanningLocus(exon_loci),
                                    strand = refloc.strand,
                                    genome = genome)
        if(locus.strand == "+"):
            ex = [(i.start - locus.start + 1, i.stop - locus.start + 1)
                  for i in exon_loci]
        else:
            ex = [(locus.stop - i.stop + 1, locus.stop - i.start + 1)
                  for i in exon_loci]

        return MemGene(name = name, locus = locus, exons = sorted(ex))

        # TODO: add option for CDS from largest ORF

    def Name(self):
        """Gene name as string"""
        return self.__name

    def SetName(self, name):
        """Rename gene"""
        self.__name = name

    def Locus(self):
        """Return locus struct"""
        return self.__locus

    def Exons(self):
        """Return exons as (first, last) list relative to genomic seq."""
        return self.__exons

    def Cds(self):
        """Return cds regions as (first, last) list relative to transcript seq."""
        return self.__cds

    def SetExons(self, exons):
        """Set exons to (first, last) list."""
        # TODO: add validation
        self.__exons = exons

    def SetCds(self, cds):
        """Set cds to (first, last) list."""
        # TODO: add validation
        self.__cds = cds

class GeneSet:
    """A set of Genes.  Provides support for timestamped addition,
    removal, and modification of genes.  At this level, the interface
    is read-only."""
    class Error(BaseException):
        def __init__(self, e = "GeneSet error"):
            self.e = e
        def __repr__(self):
            return self.e
        def __str__(self):
            return self.e

    def __getitem__(self, i):
        raise GeneSet.Error("__getitem__ not implemented")

    def __len__(self):
        raise GeneSet.Error("__len__ not implemented")

    def items(self):
        raise GeneSet.Error("items not implemented")

    def __iter__(self):
        for (name, gene) in self.items():
            yield gene

    def AddGenes(self, newgenes = [], timestamp = None):
        """Add a list of genes to the set.  Genes with the same name
        as existing genes in the set will be treated as updates and
        will overwrite them."""
        raise GeneSet.Error("AddGenes not implemented")

class MemGeneSet(GeneSet):
    """In-memory implementation of GeneSet.  Adds write access to
    the GeneSet."""
    def __init__(self):
        """Create an empty MemGeneSet."""
        # Note: assumes uniquely named genes.  This is a problem for
        #       broken gene sets (e.g. Y. lippolytica) but perhaps
        #       we don't mind.
        self.genes = {}

    def __getitem__(self, i):
        # Note: any name fixing should be implemented at a higher level.
        return self.genes[i]

    def __len__(self):
        return len(self.genes)

    def items(self):
        return self.genes.items()

    def values(self):
        return self.genes.values()
    
    def AddGenes(self, newgenes = [], timestamp = None):
        """Add a list of genes to the set.  Genes with the same name
        as existing genes in the set will be treated as updates and
        will overwrite them."""
        for i in newgenes:
            self.genes[i.Name()] = i

        # TODO: Check for collisions.  Where collisions result in
        #       a change (genes[i.Name()] != i) make a note in the
        #       timestamped changelog.  Where there is no collision,
        #       make a note in the timestamped add log.

        # Note that most of the logic for updating a GSC set from a
        # FASTA file is pushed up to the client.

        # Note that this implementation allows newgenes to be a heterogenous
        # list of Gene subclasses (e.g., the client can mix in memory
        # instances with database references).  I think that this is fine.
        # It may turn out that this implementation is also ok for DbGeneSet.
        # Otherwise, DbGeneSet will need to make explicit use of the Gene
        # interface to switch between Gene representations --> this may
        # be best done by giving the concrete Gene classes copy constructors
        # based on the base class interface.

    @classmethod
    def fromGbrowse2Gff3(cls, fp, genome = None):
        """Initialize a gene set from fp, a GFFv3 formatted file stream.
        
        There are multiple conventions for representing gene sets as GFF
        (BROAD GTF, CGD/AspGD, SGD, Gbrowse2, ...)
        This function assumes the Gbrowse2 convention where:
          Each gene has one "gene" feature, spanning all sub-features.
          The name of the gene is stored in the "Name" attribute of the
            "gene" feature.
          There is one "exon" feature per exon.
          There is one "cds" feature per disjoint coding sequence on the genome.
          All "cds" have a phase of 0 (i.e., they are collectively 1 ORF)
          All sub-features give the "gene" feature as their parent.
        """
        # Parse and index features
        gff = Gff3file.fromFile(fp)

        genes = []
        
        for gene in gff.type_to_features["gene"]:
            locus = gene.Locus()
            ref = locus.ref
            start = locus.start
            stop = locus.stop
            strand = locus.strand
            name = gene.attributes["Name"][0]

            if(locus.strand == "+"):
                transform = lambda x : (x.Locus().start - start + 1,
                                        x.Locus().stop - start + 1)
            else:
                transform = lambda x : (stop - x.Locus().stop + 1,
                                        stop - x.Locus().start + 1)

            # exons relative to "gene" coordinates
            exons = [transform(i) for i in gff.children[gene]
                     if(i.type == "exon")]
            
            # CDS relative to "gene" coordinates
            t_cds = [transform(i) for i in gff.children[gene]
                     if(i.type == "cds")]

            # Map cds to "transcript" coordinates based on exons

            # Assumption: Each CDS feature is completely contained by one
            #             and only one exon.

            cds = []
            offset = 0
            for i in exons:
                for j in range(len(t_cds) - 1, -1, -1):
                    if((i[0] <= t_cds[j][0]) and
                       (i[1] >= t_cds[j][1])):
                        new_cds = (t_cds[j][0] - i[0] + offset + 1,
                                   t_cds[j][1] - i[0] + offset + 1)
                        # Fuse CDS features that are adjacent in the transcript
                        if((len(cds) > 0) and (new_cds[0] == cds[-1][1]+1)):
                            assert(cds[-1][0] < new_cds[0] <= new_cds[1])
                            cds[-1] = (cds[-1][0], new_cds[1])
                        else:
                            cds.append(new_cds)
                        t_cds = t_cds[:j]+t_cds[j+1:]
                offset += i[1] - i[0] + 1
            if(len(t_cds) > 0):
                raise IndexError("%d CDS not contained in exons" % (
                    len(t_cds)))

            genes.append(MemGene(name = name,
                                 locus = Locus(ref = ref, 
                                               start = start,
                                               stop = stop,
                                               strand = strand,
                                               genome = genome),
                                 exons = exons,
                                 cds = cds))
        geneset = cls()
        geneset.AddGenes(genes)
        return geneset

class Contig:
    def __init__(self, name, length, assembly = None, genome = None):
        self.name = name
        self.length = int(length)
        self.assembly = assembly
        self.genome = genome
        self._seq = None

    def getslice(self, i, j):
        if(self._seq is None):
            self._initSeq()
        return self._seq[i:j]

    def __getitem__(self, i):
        if(isinstance(i, slice)):
            return self.getslice(i.start, i.stop)
        if(self._seq is None):
            self._initSeq()
        return self._seq[i]

    def __str__(self):
        return str(self[0:self.length])

    def __len__(self):
        return self.length

    def Complement(self):
        return str(DnaSequence(str(self)).Complement())

    def _initSeq(self):
        self._seq = self.assembly[self.name]

    def Locus(self):
        return Locus(ref = self.name, start = 1, stop = len(self),
                     strand = "+", genome = self.genome)
    
if(__name__ == "__main__"):
    print("Hello, world")
